services:
  osrs-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    image: osrs-mcp:latest
    container_name: osrs-mcp-server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    volumes:
      - ./config:/app/config:ro
    networks:
      - mcp-network

  mcp-inspector:
    image: ghcr.io/modelcontextprotocol/inspector:latest
    container_name: mcp-inspector
    restart: unless-stopped
    command: ["http://osrs-mcp:3000/mcp"]
    environment:
      - HOST=0.0.0.0
      - DANGEROUSLY_OMIT_AUTH=true
    ports:
      - "6274:6274"
      - "6277:6277"
    networks:
      - mcp-network
    depends_on:
      - osrs-mcp

networks:
  mcp-network:
    driver: bridge